# fly.toml app configuration file generated for shy-paper-5701 on 2023-05-23T21:28:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-paper-5701"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
